spring.application.name=vvm-pavers

spring.datasource.url=jdbc:postgresql://ep-dark-block-at2zu90t-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner
spring.datasource.password=npg_9fJT6CRQqXAH

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:9090}

